# .github/workflows/update_readme.yml
name: Update Rust trending

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch: # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions: # Add this block
      contents: write # This allows the push to succeed
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run Rust program
        run: cargo run
        working-directory: rust
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # Only commit if changes exist
          git diff --quiet && git diff --staged --quiet || git commit -m "Update trending Rust repositories"

          # 1. Fetch the latest from remote
          git fetch origin main

          # 2. Rebase and favor the local "Trending" changes if a conflict occurs
          git rebase -X ours origin/main || git rebase --abort

          # 3. Push the clean result
          git push origin main
